# 公式紹介文から抽出した料理タグ（検索キーワード用）。日本語＋ローマ字で曖昧検索に対応。
CUISINE_TAGS = {
 "Boost Juice": "ジュースjuice-smoothie",
 "Burger King": "バーガーburger",
 "CU MART": "韓国korean",
 "Dee Coffee": "デザートdessert-cake コーヒーcoffee-cafe",
 "DONQ/Mini One": "ベーカリーbakery",
 "Dunkin'": "デザートdessert-cake コーヒーcoffee-cafe ドーナツdonut",
 "Empire Sushi": "和食 寿司sushi",
 "Famous Amos": "デザートdessert-cake ベーカリーbakery クッキーcookie",
 "Happy Potato": "スナックsnack",
 "Hawker Chan": "チキンchicken 中華点心chinese",
 "Hercaa": "抹茶matcha",
 "Hot & Roll, IMP'za": "洋食western デザートdessert-cake",
 "JJ Chili Pan Mee": "中華点心chinese ハラルhalal 麺noodle",
 "Kita Dining": "洋食western シーフードseafood チキンchicken",
 "Koong Woh Tong": "デザートdessert 漢方herbal",
 "Lian Jie Noodle House": "麺noodle チキンchicken",
 "Little Wok Fried Rice": "中華点心chinese 炒飯friedrice",
 "Llao Llao": "アイスicecream フローズンヨーグルトfroyo",
 "Lol Soon Kee Desserts": "中華点心chinese デザートdessert-cake",
 "Mee Hiris China Muslim": "中華点心chinese ハラルhalal 麺noodle",
 "Memang Meow Kopitiam": "デザートdessert-cake コーヒーcoffee-cafe",
 "Menya Shi Shi Do": "和食 ラーメンramen",
 "Mr. Chizu": "デザートdessert-cake チーズcheese",
 "Oiso Korean Traditional Cuisine & Cafe": "韓国korean コーヒーcoffee-cafe",
 "Papafry": "韓国korean チキンchicken",
 "ParaThai": "タイthai",
 "Sai Kee Authentic Home Cuisine": "中華点心chinese",
 "Seoul Garden": "韓国korean ハラルhalal 焼肉bbq",
 "Sukiya": "和食 丼カツdon-katsu カレーcurry チキンchicken ハラルhalal",
 "Sun San Curry": "和食 カレーcurry",
 "Sushi King": "和食 寿司sushi",
 "Syok Makan": "中華点心chinese 洋食western",
 "The Chicken Rice Shop": "チキンchicken チキンライスchickenrice",
 "Torigen Chicken Ramen": "和食 ラーメンramen チキンchicken",
 "Yakiniku Botan+": "和食 和牛wagyu 焼肉yakiniku-bbq",
 "Doko Koko Café": "コーヒーcoffee-cafe",
 "Dome Cafe": "デザートdessert-cake コーヒーcoffee-cafe",
 "eclipse café and meal": "洋食western デザートdessert-cake ベーカリーbakery コーヒーcoffee-cafe",
 "FatFire": "焼肉bbq シーフードseafood バーbar",
 "Giglio Restaurant": "洋食western イタリアンitalian デザートdessert-cake",
 "Go Wei (Go 味)": "中華点心chinese",
 "Hookie Dookie": "居酒屋バーizakaya-bar 洋食western",
 "Hut Dining Buffet": "食べ放題buffet",
 "Ikkyu Izakaya": "和食 寿司sushi 居酒屋izakaya-bar",
 "Koboreya": "和食",
 "Koryouriya Tsudoi": "和食 小料理",
 "KWING": "居酒屋バーizakaya-bar 韓国korean チキンchicken",
 "LaLapop by Frozen": "アイスicecream デザートdessert",
 "Matcha Eight": "和食 アイスicecream 抹茶matcha デザートdessert",
 "MY THAI BAR": "居酒屋バーizakaya-bar タイthai",
 "ORBcafe": "コーヒーcoffee-cafe",
 "Padi Malaya": "マレー系malay-nasi ハラルhalal",
 "Sakanoue Café": "和食 コーヒーcoffee-cafe",
 "Shabu-yo": "和食 すき焼きsukiyaki しゃぶしゃぶshabu 食べ放題buffet",
 "Sugar and I": "デザートdessert-cake ケーキcake",
 "Sushi Yoshi": "和食 寿司sushi",
 "TOUS les JOURS": "デザートdessert-cake ベーカリーbakery",
 "V88": "居酒屋バーizakaya-bar コーヒーcoffee-cafe",
 "Wagyu and Rice": "和牛wagyu 洋食western バーガーburger 和食",
 "WAGYU DAGIN": "和食 和牛wagyu すき焼きsukiyaki しゃぶしゃぶshabu 焼肉yakiniku-bbq 食べ放題buffet",
 "YOYO Bird's Nest Dessert Expert": "デザートdessert-cake",
 "ZUS Coffee": "コーヒーcoffee-cafe",
 "Lucky Cup": "和食 コーヒーcoffee-cafe 抹茶matcha",
 "Secret Recipe": "デザートdessert-cake ケーキcake コーヒーcoffee-cafe",
 "Subway": "ベーカリーbakery サンドイッチsandwich",
 "LeTen Dim Sum": "中華点心chinese 点心dimsum",
 "Akiba Ramen": "和食 ラーメンramen",
 "Ayam Penyet Best": "チキンchicken マレー系malay ハラルhalal",
 "Cocosan": "タイthai",
 "Dee Thai Restaurant": "タイthai",
 "Doutor": "和食 コーヒーcoffee-cafe",
 "ENAK ENAK express": "マレー系malay-nasi ハラルhalal",
 "Killiney": "ベーカリーbakery コーヒーcoffee-cafe",
 "KorFry": "韓国korean チキンchicken デザートdessert-cake",
 "Meow Western": "焼肉bbq 洋食western",
 "MIXUE": "アイスicecream デザートdessert",
 "MR CORN": "スナックsnack デザートdessert コーンcorn",
 "NAM HEONG SINCE 1938": "チキンchicken チキンライスchickenrice",
 "Nasi Lemak by Memang": "マレー系malay-nasi コーヒーcoffee-cafe ハラルhalal",
 "Pizza Gao! Gao!": "洋食western ピザpizza ベーカリーbakery",
 "POKOK KL Cafe": "ベーカリーbakery コーヒーcoffee-cafe",
 "Stack'd": "バーガーburger チキンchicken",
 "SUKI-YA": "すき焼きsukiyaki しゃぶしゃぶshabu 食べ放題buffet 和食",
 "Tealive": "タピオカbubbletea ドリンクdrink",
 "Wok On Fire": "中華点心chinese 炒めwok",
 # 補足（有名店・明らかなもの）
 "Ippudo": "和食 ラーメンramen 豚骨tonkotsu",
 "Gong Cha": "タピオカbubbletea ミルクティーmilktea",
 "Ben Gong's Tea": "タピオカbubbletea ミルクティーmilktea",
 "I Love Yoo!": "中華点心chinese 揚げパンyoutiao 粥congee",
 "Container Kebab": "ケバブkebab ハラルhalal",
 "Ngam Ngam": "タイthai",
}
