# 各店の特徴語（公式紹介文由来・厳選）。検索キーワードに追加。
# 「suit」がsuit your…に誤反応した分と不確かな語は除外済み。
SPECIFIC_TAGS = {
 "AM Skin Factories": "脱毛除毛",
 "Brooks, Pressio": "ランニングシューズ",
 "Burger King": "ハンバーグ",
 "Container Kebab": "ケバブ",
 "Dunkin'": "ドーナツ",
 "Fleur": "シルク絹",
 "Hawker Chan": "チキンライス海南",
 "Hot & Roll, IMP'za": "クレープ",
 "Killiney": "食パントースト チキンライス海南",
 "Leather Avenue": "レザー革製品",
 "L'OCCITANE": "オーガニック",
 "MR CORN": "ワッフル",
 "MXD Hobby": "ガチャカプセル",
 "NAM HEONG SINCE 1938": "チキンライス海南",
 "Nasi Lemak by Memang": "ナシレマ",
 "NOT ONLY TOY": "プラモデルガンプラ フィギュアコレクション",
 "OnlyKorea": "韓国コスメKビューティ 脱毛除毛",
 "Regal": "レザー革製品",
 "Rev Runnr": "ランニングシューズ",
 "SEMBONIA": "レザー革製品",
 "Sugar and I": "ボンボローニ",
 "SUKI-YA": "火鍋",
 "The Chicken Rice Shop": "チキンライス海南",
 "V88": "ヴィンテージ古着",
 "Wagyu and Rice": "ステーキ ハンバーグ",
 "WAGYU DAGIN": "A5等級",
 "Yakiniku Botan+": "A5等級 宮崎牛",
}
